"""Add comentario to ModeloIPV

Revision ID: 7a5988a22b87
Revises: 
Create Date: 2025-07-14 21:02:30.445246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a5988a22b87'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo_ipv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentario', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo_ipv', schema=None) as batch_op:
        batch_op.drop_column('comentario')

    # ### end Alembic commands ###
