"""Add comentario to InventarioDiario

Revision ID: b29f7ae8b140
Revises: 7a5988a22b87
Create Date: 2025-07-14 21:16:34.813003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29f7ae8b140'
down_revision = '7a5988a22b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inventario_diario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentario', sa.Text(), nullable=True))

    with op.batch_alter_table('modelo_ipv', schema=None) as batch_op:
        batch_op.drop_column('comentario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modelo_ipv', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentario', sa.TEXT(), nullable=True))

    with op.batch_alter_table('inventario_diario', schema=None) as batch_op:
        batch_op.drop_column('comentario')

    # ### end Alembic commands ###
